lite:
  version: "0.11.1"
  size: 230kb
  x86url: https://github.com/OneQuick/OneQuick.net/releases/download/bin/OneQuick.Lite.0.11.1.3518.x86.zip
  x64url: https://github.com/OneQuick/OneQuick.net/releases/download/bin/OneQuick.Lite.0.11.1.3519.x64.zip
  launch: OneQuick.exe
  v1note: 预览版
  v2note: 将配置文件位置从LocalAppData改到用户文档目录，无法自动升级的话，请手动到官网升级。
  v3note: 
