lite:
  version: "0.1.0"
  size: 230kb
  x86url: https://github.com/OneQuick/OneQuick.net/releases/download/bin/OneQuick.Lite.0.11.0.2869.x86.zip
  x64url: https://github.com/OneQuick/OneQuick.net/releases/download/bin/OneQuick.Lite.0.11.0.2870.x64.zip
  launch: OneQuick.exe
  v1note: 预览版
  v2note: 将配置文件位置从LocalAppData改到用户文档目录，请手动到官网升级。
  v3note: 
