lite:
  version: "1.0.0"
  size: 250kb
  x86url: https://github.com/OneQuick/OneQuick.net/releases/download/bin/OneQuick.Lite.1.0.0.39256.x86.zip
  x64url: https://github.com/OneQuick/OneQuick.net/releases/download/bin/OneQuick.Lite.1.0.0.39257.x64.zip
  launch: OneQuick.exe
  v1note: 增加快速搜索功能。修复大量bug。
  v2note: 增加快速搜索功能。修复大量bug。
  v3note: 增加快速搜索功能。修复大量bug。
